<h3>Add Courses here: </h3>
<?php if($this->session->flashdata('addCourse')): ?>
 	<p class="alert alert-dismissable alert-success"/><?php echo $this->session->flashdata('addCourse'); ?></<p>
<?php endif; ?>
<?php echo validation_errors('<p class="alert alert-dismissable alert-danger"/>');

	  $attributes = array('id'=> 'addCourse','class'=>'form-horizontal'); 
	  echo form_open('admin_register/addCourse_Validation', $attributes); ?>
<!--DropDown to Select Department-->
<p>
	<p>Select Department: </p> 
	<?php
		$options = array();
		
		foreach($results as $row)
		{
			$options[$row->DepartmentCode] = $row->DepartmentCode; 
		}
		
		echo form_dropdown('DepartmentCode',$options);
	?>
</p>	  

<!--Course Num-->
<p>
	<?php echo form_label('Course Number: '); ?>
	<?php
	$data = array(
				  'name'  => 'CourseNum',
				  'value' => set_value('CourseNum')
				  );
	?>
	<?php echo form_input($data);?>
</p>

<!--Course Title-->
<p>
	<?php echo form_label('Course Title: '); ?>
	<?php
	$data = array(
				  'name'  => 'CourseTitle',
				  'value' => set_value('CourseTitle')
				  );
	?>
	<?php echo form_input($data);?>
</p>

<!--Number of Credits-->
<p>
	<?php echo form_label('Number of Credits: '); ?>
	<?php
	$data = array(
				  'name'  => 'NumCredits',
				  'value' => set_value('NumCredits')
				  );
	?>
	<?php echo form_input($data);?>
</p>

<!--Prereq1-->
<p>
	<?php echo form_label('PreReg. 1rst [Course ID] (Leave Blank if none): '); ?>
	<?php
	$data = array(
				  'name'  => 'Prereq1',
				  'value' => set_value('Prereq1')
				  );
	?>
	<?php echo form_input($data);?>
</p>

<!--Prereq2-->
<p>
	<?php echo form_label('PreReg. 2nd [Course ID] (Leave Blank if none): '); ?>
	<?php
	$data = array(
				  'name'  => 'Prereq2',
				  'value' => set_value('Prereq2')
				  );
	?>
	<?php echo form_input($data);?>
</p>

<!--Prereq3-->
<p>
	<?php echo form_label('PreReg. 3rd [Course ID] (Leave Blank if none): '); ?>
	<?php
	$data = array(
				  'name'  => 'Prereq3',
				  'value' => set_value('Prereq3')
				  );
	?>
	<?php echo form_input($data);?>
</p>

<p>
	<?php	  $data = array('name'   => 'submit',
		  					'class'  => 'btn btn-primary',
		  					'value'  => 'Register');
		  				
		  echo form_submit($data);
		  
	?>
</p>
<?php echo form_close();?>
<footer>(Please Note: Course ID are autogenerated and can be Viewed under the option <strong>List All courses.</strong>)</footer>